# Generated by Django 3.2.8 on 2021-11-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_course_creator',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as a course creator. '),
        ),
    ]
