# Generated by Django 3.2.8 on 2021-11-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_course_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_publisher',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as a publisher. '),
        ),
    ]
